"""
Mockup service — build attractive LISTING/AD images from the REAL delivered
design (step 100h).

Why this exists: for digital single-image products the marketing images used to
be an INDEPENDENT text-to-image generation, which depicts a genuinely different
illustration than the delivered file (a different dinosaur) — the consistency
gate correctly rejects it and no prompt/remake fixes it. Simply showing the flat
delivered file (100g) is honest but (a) looks like a bare product, not an ad, and
(b) lets anyone lift the clean file straight from the listing.

This service is how real Etsy digital sellers solve it: composite the ACTUAL
delivered design into a realistic scene (a framed print on a wall, a print in a
desk flat-lay) so the ad looks professional AND shows the true product. The
design is composited at a PERSPECTIVE ANGLE (foreshortened), so the preview shows
what the buyer gets but a screenshot isn't a clean, flat, usable copy of the
product — no watermark needed. Because the scene is built from the real design,
it can never misrepresent (no consistency conflict), and only the clean, straight
file is delivered after purchase.

The photorealistic SCENE (an empty wall / empty desk) is generated by the image
provider — it contains no product-specific design, so it can't mismatch. The
real design is composited on top with PIL (framing, matte, paper, soft shadow),
never regenerated. A deterministic PIL studio/desk background is used as a
fallback if generation fails, so a mockup is always produced.
"""
import asyncio
import base64
import logging
import random
from io import BytesIO
from pathlib import Path

import httpx
from PIL import Image, ImageDraw, ImageFilter, ImageOps

from app.core.paths import get_data_dir
from app.core.providers.image_manager import ImageProviderManager
from config import settings

logger = logging.getLogger("ai-factory")

# P3-6: cache generated background scenes (empty wall / desk — product-agnostic)
# and reuse them, instead of paying ~$0.04 per scene per product. Build up to
# this many per role, then pick randomly for variety at zero cost.
_MAX_CACHED_SCENES = 5


class MockupService:
    """Composites the real delivered design into an attractive listing/ad image.
    Text-to-image is used ONLY for the empty background scene; the product itself
    is the real design, composited with PIL.

    3-2: the perspective foreshortening is the FIRST line of copy-protection (a
    screenshot isn't a clean flat file), but for formats where the preview IS
    essentially the product (coloring pages, phone wallpapers) it's weak — a
    crop/un-warp yields a usable file. For those formats (settings.WATERMARK_FORMATS)
    a tiled semi-transparent shop-name watermark is baked into the DESIGN LAYER
    before compositing, so it follows the perspective and can't be trivially
    cropped out. Delivery files stay clean — only the public preview is marked."""

    # Empty-scene prompts. They deliberately demand blank negative space so the
    # composited framed print / print sits cleanly, with no competing artwork.
    SCENES = {
        "framed": (
            "Professional interior photograph of a softly lit minimalist wall in warm "
            "neutral tones, gentle natural daylight with a soft shadow gradient. A "
            "completely BLANK empty wall — absolutely NO frames, NO posters, NO artwork, "
            "NO shelves, NO text and NO objects of any kind — clean empty negative space. "
            "Photorealistic, shallow depth of field."
        ),
        "flatlay": (
            "Top-down flat-lay photograph of a clean light-oak wooden desk. A small "
            "potted green plant in one corner, a ceramic coffee cup and two wooden pencils "
            "near the edges, soft natural window light. A large EMPTY blank space in the "
            "CENTER with absolutely nothing on it — no paper, no card, no text. "
            "Photorealistic, tasteful, minimal."
        ),
    }

    def __init__(self, image_provider=None):
        # Lazy: only resolve a provider if we actually generate a scene, so the
        # service works with the PIL fallback even when no image provider is
        # registered (and degrades gracefully if one is unavailable).
        self._image_provider = image_provider

    # ── Public API ────────────────────────────────────────────────────────────

    def build_mockup_bytes(
        self,
        design_path,
        role: str = "framed",
        size: int = 1024,
        product_format: str = None,
    ) -> bytes:
        """Return PNG bytes of a `size`x`size` mockup of the real design in a
        `role` scene ('framed' or 'flatlay'). The design is composited at a
        PERSPECTIVE ANGLE (foreshortened); for `product_format` in
        settings.WATERMARK_FORMATS a tiled watermark is also baked into the
        design layer (3-2)."""
        design = Image.open(design_path).convert("RGB")
        design = self._maybe_watermark(design, product_format)

        scene = self._scene(role, size)

        if role == "flatlay":
            obj = self._flat_print(design)
            obj = self._perspective(obj, squeeze=0.16, axis="y")  # page receding on the desk
            fill = 0.66
            y_nudge = 0.0
        else:
            obj = self._framed_print(design)
            obj = self._perspective(obj, squeeze=0.15, axis="x")  # framed art viewed off-axis
            fill = 0.66
            y_nudge = -0.03  # hang slightly above centre on the wall

        target_w = int(size * fill)
        scale = target_w / obj.width
        obj = obj.resize((max(1, int(obj.width * scale)), max(1, int(obj.height * scale))), Image.LANCZOS)

        base = scene.convert("RGBA")
        x = (size - obj.width) // 2
        y = (size - obj.height) // 2 + int(size * y_nudge)
        base.alpha_composite(obj, (x, y))
        out = base.convert("RGB")

        buf = BytesIO()
        out.save(buf, format="PNG")
        return buf.getvalue()

    def build_flatlay_bytes(self, page_paths, size: int = 1024, product_format: str = None) -> bytes:
        """Return PNG bytes of several REAL pages (e.g. a multi-page PDF planner)
        fanned out on a desk scene, each foreshortened + rotated so the preview
        shows the actual pages the buyer gets but isn't a usable flat copy. A
        single page falls back to the normal flat-lay."""
        pages = [p for p in (page_paths or []) if p][:4]
        if not pages:
            raise ValueError("no pages to compose a flat-lay")
        if len(pages) == 1:
            return self.build_mockup_bytes(pages[0], role="flatlay", size=size, product_format=product_format)

        base = self._scene("flatlay", size).convert("RGBA")
        angles = [-9, 6, -3, 8]
        offx = [-0.13, 0.12, -0.05, 0.15]
        offy = [-0.11, 0.10, 0.03, 0.13]
        target_w = int(size * 0.50)
        for i, pp in enumerate(pages):
            design = Image.open(pp).convert("RGB")
            design = self._maybe_watermark(design, product_format)
            card = self._flat_print(design, rotate=0)            # paper + shadow, no baked tilt
            card = self._perspective(card, squeeze=0.12, axis="y")
            scale = target_w / card.width
            card = card.resize((max(1, int(card.width * scale)), max(1, int(card.height * scale))), Image.LANCZOS)
            card = card.rotate(angles[i % 4], resample=Image.BICUBIC, expand=True)
            x = (size - card.width) // 2 + int(offx[i % 4] * size)
            y = (size - card.height) // 2 + int(offy[i % 4] * size)
            base.alpha_composite(card, (x, y))
        out = base.convert("RGB")
        buf = BytesIO()
        out.save(buf, format="PNG")
        return buf.getvalue()

    # ── Watermark (3-2) ────────────────────────────────────────────────────────
    def _maybe_watermark(self, design: Image.Image, product_format: str) -> Image.Image:
        """Bake a tiled, diagonal, semi-transparent shop-name watermark into the
        design IF this format is in settings.WATERMARK_FORMATS (formats where the
        preview is basically the product — coloring pages, phone wallpapers).
        Applied to the design layer so it foreshortens with the perspective and
        can't be cropped off. Delivery files are never touched."""
        fmts = getattr(settings, "WATERMARK_FORMATS", []) or []
        if not product_format or product_format not in fmts:
            return design
        try:
            text = (getattr(settings, "WATERMARK_TEXT", None) or getattr(settings, "SHOP_NAME", None) or "Products For All")
            w, h = design.size
            layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
            draw = ImageDraw.Draw(layer)
            # scale the font to the image; PIL default font is fine (no font files in prod)
            try:
                from PIL import ImageFont
                font = ImageFont.truetype("arial.ttf", max(16, w // 22))
            except Exception:
                from PIL import ImageFont
                font = ImageFont.load_default()
            try:
                tw = draw.textlength(text, font=font)
            except Exception:
                tw = len(text) * 10
            step_x = max(120, int(tw) + w // 8)
            step_y = max(90, h // 7)
            alpha = int(getattr(settings, "WATERMARK_ALPHA", 55))
            for yy in range(-step_y, h + step_y, step_y):
                for xx in range(-step_x, w + step_x, step_x):
                    draw.text((xx, yy), text, fill=(255, 255, 255, alpha), font=font)
                    draw.text((xx + 1, yy + 1), text, fill=(0, 0, 0, max(20, alpha - 25)), font=font)
            layer = layer.rotate(30, expand=False)
            return Image.alpha_composite(design.convert("RGBA"), layer).convert("RGB")
        except Exception as e:
            logger.warning(f"MockupService: watermark failed (proceeding unwatermarked): {e}")
            return design

    # ── Perspective tilt (pure-Python, no numpy — not available in prod) ───────

    def _perspective(self, img: Image.Image, squeeze: float = 0.15, axis: str = "x") -> Image.Image:
        """Foreshorten `img` (RGBA) so it looks viewed at a slight angle, and so
        a screenshot can't be flattened back into a clean, usable product copy.
        `axis='x'` shortens the right edge (viewed off to one side); `axis='y'`
        shortens the top edge (receding into the distance)."""
        img = img.convert("RGBA")
        w, h = img.size
        if axis == "y":
            dx = int(w * squeeze / 2)
            out_quad = [(dx, 0), (w - dx, 0), (w, h), (0, h)]  # top edge narrower
        else:
            dy = int(h * squeeze / 2)
            out_quad = [(0, 0), (w, dy), (w, h - dy), (0, h)]  # right edge shorter
        in_quad = [(0, 0), (w, 0), (w, h), (0, h)]
        coeffs = self._perspective_coeffs(out_quad, in_quad)
        return img.transform((w, h), Image.PERSPECTIVE, coeffs, Image.BICUBIC)

    def _perspective_coeffs(self, out_quad, in_quad):
        """8 PIL PERSPECTIVE coefficients mapping output->input for the 4 corner
        correspondences. Solved with plain Gaussian elimination (no numpy)."""
        A, b = [], []
        for (ox, oy), (ix, iy) in zip(out_quad, in_quad):
            A.append([ox, oy, 1, 0, 0, 0, -ox * ix, -oy * ix]); b.append(ix)
            A.append([0, 0, 0, ox, oy, 1, -ox * iy, -oy * iy]); b.append(iy)
        return self._solve(A, b)

    @staticmethod
    def _solve(A, b):
        n = len(b)
        M = [A[i][:] + [b[i]] for i in range(n)]
        for col in range(n):
            piv = max(range(col, n), key=lambda r: abs(M[r][col]))
            M[col], M[piv] = M[piv], M[col]
            pv = M[col][col]
            if abs(pv) < 1e-12:
                continue
            for r in range(n):
                if r != col and M[r][col] != 0.0:
                    f = M[r][col] / pv
                    M[r] = [M[r][k] - f * M[col][k] for k in range(n + 1)]
        return [M[i][n] / M[i][i] if abs(M[i][i]) > 1e-12 else 0.0 for i in range(n)]

    # ── Scene (generated, with a deterministic fallback) ───────────────────────

    def _scene(self, role: str, size: int) -> Image.Image:
        if getattr(settings, "MOCKUP_USE_GENERATED_SCENES", True):
            # P3-6: reuse a cached scene if we already have enough; the scene is
            # product-agnostic (empty wall/desk), so caching loses no quality.
            cache_dir = get_data_dir() / "images" / "scenes"
            cached = []
            try:
                cache_dir.mkdir(parents=True, exist_ok=True)
                cached = sorted(cache_dir.glob(f"{role}_*.png"))
            except Exception:
                pass
            if len(cached) >= _MAX_CACHED_SCENES:
                try:
                    pick = random.choice(cached)
                    scene = Image.open(pick).convert("RGB")
                    return ImageOps.fit(scene, (size, size), Image.LANCZOS)
                except Exception as e:
                    logger.warning(f"MockupService: cached scene load failed ({pick}): {e}")

            try:
                provider = self._image_provider or ImageProviderManager.get_provider()
                prompt = self.SCENES.get(role, self.SCENES["framed"])
                result = asyncio.run(
                    provider.generate_image(prompt, aspect_ratio="1:1", resolution="2K")
                )
                if result.b64_data:
                    raw = base64.b64decode(result.b64_data)
                elif result.url:
                    raw = httpx.get(result.url, timeout=60.0, follow_redirects=True).content
                else:
                    raise ValueError("image result had neither b64 nor url")
                scene = Image.open(BytesIO(raw)).convert("RGB")
                # Persist to the cache (best-effort) so future products reuse it.
                try:
                    scene.save(cache_dir / f"{role}_{len(cached)}.png", format="PNG")
                except Exception:
                    pass
                return ImageOps.fit(scene, (size, size), Image.LANCZOS)
            except Exception as e:
                logger.warning(f"MockupService: scene generation failed ({role}), using PIL fallback: {e}")
        return self._studio_bg(role, size)

    def _studio_bg(self, role: str, size: int) -> Image.Image:
        """Deterministic, always-clean fallback background: a soft studio radial
        gradient (framed) or a warm desk-tone gradient (flatlay)."""
        if role == "flatlay":
            top, bottom = (232, 222, 208), (208, 192, 170)
        else:
            top, bottom = (250, 250, 252), (223, 224, 230)
        bg = Image.new("RGB", (size, size), top)
        # vertical gradient
        grad = Image.new("L", (1, size))
        for y in range(size):
            grad.putpixel((0, y), int(255 * (y / max(1, size - 1))))
        grad = grad.resize((size, size))
        bottom_img = Image.new("RGB", (size, size), bottom)
        bg = Image.composite(bottom_img, bg, grad)
        # soft central vignette highlight
        vig = Image.new("L", (size, size), 0)
        d = ImageDraw.Draw(vig)
        d.ellipse([size * 0.12, size * 0.10, size * 0.88, size * 0.86], fill=60)
        vig = vig.filter(ImageFilter.GaussianBlur(size // 8))
        light = Image.new("RGB", (size, size), (255, 255, 255))
        bg = Image.composite(light, bg, vig)
        return bg

    # ── Product composites (real design) ───────────────────────────────────────

    def _framed_print(self, design: Image.Image) -> Image.Image:
        """A framed-print composite of the real design: white matte, dark wooden
        frame with a subtle bevel, and a soft drop shadow. Returns RGBA."""
        base_w = 660
        d = ImageOps.contain(design, (base_w, base_w), Image.LANCZOS)
        matte, frame = 30, 26
        inner_w, inner_h = d.width + 2 * matte, d.height + 2 * matte
        total_w, total_h = inner_w + 2 * frame, inner_h + 2 * frame

        art = Image.new("RGB", (total_w, total_h), (34, 28, 24))  # dark wood frame
        ImageDraw.Draw(art).rectangle(
            [frame - 3, frame - 3, total_w - frame + 2, total_h - frame + 2],
            outline=(120, 98, 74), width=2,  # bevel highlight
        )
        matte_img = Image.new("RGB", (inner_w, inner_h), (250, 250, 248))
        matte_img.paste(d, (matte, matte))
        art.paste(matte_img, (frame, frame))
        return self._with_shadow(art, offset=(0, 18), blur=20, alpha=120)

    def _flat_print(self, design: Image.Image, rotate: int = -3) -> Image.Image:
        """The real design as a printed sheet lying on a surface: thin white paper
        border, soft shadow, and an optional slight `rotate` (0 = none, used by the
        multi-page fan which applies its own per-page angle). Returns RGBA."""
        base_w = 680
        d = ImageOps.contain(design, (base_w, base_w), Image.LANCZOS)
        pad = 16
        sheet = Image.new("RGB", (d.width + 2 * pad, d.height + 2 * pad), (252, 252, 250))
        sheet.paste(d, (pad, pad))
        card = self._with_shadow(sheet, offset=(0, 14), blur=16, alpha=105)
        return card.rotate(rotate, resample=Image.BICUBIC, expand=True) if rotate else card

    def _with_shadow(self, img_rgb: Image.Image, offset=(0, 16), blur=18, alpha=120) -> Image.Image:
        pad = blur * 3
        w, h = img_rgb.size
        canvas = Image.new("RGBA", (w + 2 * pad, h + 2 * pad), (0, 0, 0, 0))
        shadow = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        ox, oy = offset
        ImageDraw.Draw(shadow).rectangle(
            [pad + ox, pad + oy, pad + w + ox, pad + h + oy], fill=(0, 0, 0, alpha)
        )
        shadow = shadow.filter(ImageFilter.GaussianBlur(blur))
        canvas.alpha_composite(shadow)
        canvas.alpha_composite(img_rgb.convert("RGBA"), (pad, pad))
        return canvas
