"""
Mockup service — build attractive LISTING/AD images from the REAL delivered
design (step 100h).

Why this exists: for digital single-image products the marketing images used to
be an INDEPENDENT text-to-image generation, which depicts a genuinely different
illustration than the delivered file (a different dinosaur) — the consistency
gate correctly rejects it and no prompt/remake fixes it. Simply showing the flat
delivered file (100g) is honest but (a) looks like a bare product, not an ad, and
(b) lets anyone lift the clean file straight from the listing.

This service is how real Etsy digital sellers solve it: composite the ACTUAL
delivered design into a realistic scene (a framed print on a wall, a print in a
desk flat-lay) so the ad looks professional AND shows the true product, then
watermark it so the public preview can't be used as the deliverable. Because the
scene is built from the real design, it can never misrepresent (no consistency
conflict), and only the clean, unwatermarked file is delivered after purchase.

The photorealistic SCENE (an empty wall / empty desk) is generated by the image
provider — it contains no product-specific design, so it can't mismatch. The
real design is composited on top with PIL (framing, matte, paper, soft shadow),
never regenerated. A deterministic PIL studio/desk background is used as a
fallback if generation fails, so a mockup is always produced.
"""
import asyncio
import base64
import logging
from io import BytesIO
from pathlib import Path

import httpx
from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps

from app.core.providers.image_manager import ImageProviderManager
from config import settings

logger = logging.getLogger("ai-factory")


class MockupService:
    """Composites the real delivered design into an attractive, watermarked
    listing/ad image. Text-to-image is used ONLY for the empty background scene;
    the product itself is the real design, composited with PIL."""

    # Empty-scene prompts. They deliberately demand blank negative space so the
    # composited framed print / print sits cleanly, with no competing artwork.
    SCENES = {
        "framed": (
            "Professional interior photograph of a softly lit minimalist wall in warm "
            "neutral tones, gentle natural daylight with a soft shadow gradient. A "
            "completely BLANK empty wall — absolutely NO frames, NO posters, NO artwork, "
            "NO shelves, NO text and NO objects of any kind — clean empty negative space. "
            "Photorealistic, shallow depth of field."
        ),
        "flatlay": (
            "Top-down flat-lay photograph of a clean light-oak wooden desk. A small "
            "potted green plant in one corner, a ceramic coffee cup and two wooden pencils "
            "near the edges, soft natural window light. A large EMPTY blank space in the "
            "CENTER with absolutely nothing on it — no paper, no card, no text. "
            "Photorealistic, tasteful, minimal."
        ),
    }

    def __init__(self, image_provider=None):
        # Lazy: only resolve a provider if we actually generate a scene, so the
        # service works with the PIL fallback even when no image provider is
        # registered (and degrades gracefully if one is unavailable).
        self._image_provider = image_provider

    # ── Public API ────────────────────────────────────────────────────────────

    def build_mockup_bytes(
        self,
        design_path,
        role: str = "framed",
        size: int = 1024,
        watermark_text: str = "PREVIEW",
    ) -> bytes:
        """Return PNG bytes of a `size`x`size` watermarked mockup of the real
        design in a `role` scene ('framed' or 'flatlay')."""
        design = Image.open(design_path).convert("RGB")

        scene = self._scene(role, size)

        if role == "flatlay":
            obj = self._flat_print(design)
            fill = 0.60
            y_nudge = 0.0
        else:
            obj = self._framed_print(design)
            fill = 0.62
            y_nudge = -0.03  # hang slightly above centre on the wall

        target_w = int(size * fill)
        scale = target_w / obj.width
        obj = obj.resize((max(1, int(obj.width * scale)), max(1, int(obj.height * scale))), Image.LANCZOS)

        base = scene.convert("RGBA")
        x = (size - obj.width) // 2
        y = (size - obj.height) // 2 + int(size * y_nudge)
        base.alpha_composite(obj, (x, y))
        out = base.convert("RGB")
        out = self._watermark(out, watermark_text)

        buf = BytesIO()
        out.save(buf, format="PNG")
        return buf.getvalue()

    # ── Scene (generated, with a deterministic fallback) ───────────────────────

    def _scene(self, role: str, size: int) -> Image.Image:
        if getattr(settings, "MOCKUP_USE_GENERATED_SCENES", True):
            try:
                provider = self._image_provider or ImageProviderManager.get_provider()
                prompt = self.SCENES.get(role, self.SCENES["framed"])
                result = asyncio.run(
                    provider.generate_image(prompt, aspect_ratio="1:1", resolution="2K")
                )
                if result.b64_data:
                    raw = base64.b64decode(result.b64_data)
                elif result.url:
                    raw = httpx.get(result.url, timeout=60.0, follow_redirects=True).content
                else:
                    raise ValueError("image result had neither b64 nor url")
                scene = Image.open(BytesIO(raw)).convert("RGB")
                return ImageOps.fit(scene, (size, size), Image.LANCZOS)
            except Exception as e:
                logger.warning(f"MockupService: scene generation failed ({role}), using PIL fallback: {e}")
        return self._studio_bg(role, size)

    def _studio_bg(self, role: str, size: int) -> Image.Image:
        """Deterministic, always-clean fallback background: a soft studio radial
        gradient (framed) or a warm desk-tone gradient (flatlay)."""
        if role == "flatlay":
            top, bottom = (232, 222, 208), (208, 192, 170)
        else:
            top, bottom = (250, 250, 252), (223, 224, 230)
        bg = Image.new("RGB", (size, size), top)
        # vertical gradient
        grad = Image.new("L", (1, size))
        for y in range(size):
            grad.putpixel((0, y), int(255 * (y / max(1, size - 1))))
        grad = grad.resize((size, size))
        bottom_img = Image.new("RGB", (size, size), bottom)
        bg = Image.composite(bottom_img, bg, grad)
        # soft central vignette highlight
        vig = Image.new("L", (size, size), 0)
        d = ImageDraw.Draw(vig)
        d.ellipse([size * 0.12, size * 0.10, size * 0.88, size * 0.86], fill=60)
        vig = vig.filter(ImageFilter.GaussianBlur(size // 8))
        light = Image.new("RGB", (size, size), (255, 255, 255))
        bg = Image.composite(light, bg, vig)
        return bg

    # ── Product composites (real design) ───────────────────────────────────────

    def _framed_print(self, design: Image.Image) -> Image.Image:
        """A framed-print composite of the real design: white matte, dark wooden
        frame with a subtle bevel, and a soft drop shadow. Returns RGBA."""
        base_w = 660
        d = ImageOps.contain(design, (base_w, base_w), Image.LANCZOS)
        matte, frame = 30, 26
        inner_w, inner_h = d.width + 2 * matte, d.height + 2 * matte
        total_w, total_h = inner_w + 2 * frame, inner_h + 2 * frame

        art = Image.new("RGB", (total_w, total_h), (34, 28, 24))  # dark wood frame
        ImageDraw.Draw(art).rectangle(
            [frame - 3, frame - 3, total_w - frame + 2, total_h - frame + 2],
            outline=(120, 98, 74), width=2,  # bevel highlight
        )
        matte_img = Image.new("RGB", (inner_w, inner_h), (250, 250, 248))
        matte_img.paste(d, (matte, matte))
        art.paste(matte_img, (frame, frame))
        return self._with_shadow(art, offset=(0, 18), blur=20, alpha=120)

    def _flat_print(self, design: Image.Image) -> Image.Image:
        """The real design as a printed sheet lying on a surface: thin white paper
        border, slight rotation, soft shadow. Returns RGBA."""
        base_w = 680
        d = ImageOps.contain(design, (base_w, base_w), Image.LANCZOS)
        pad = 16
        sheet = Image.new("RGB", (d.width + 2 * pad, d.height + 2 * pad), (252, 252, 250))
        sheet.paste(d, (pad, pad))
        card = self._with_shadow(sheet, offset=(0, 14), blur=16, alpha=105)
        return card.rotate(-3, resample=Image.BICUBIC, expand=True)

    def _with_shadow(self, img_rgb: Image.Image, offset=(0, 16), blur=18, alpha=120) -> Image.Image:
        pad = blur * 3
        w, h = img_rgb.size
        canvas = Image.new("RGBA", (w + 2 * pad, h + 2 * pad), (0, 0, 0, 0))
        shadow = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        ox, oy = offset
        ImageDraw.Draw(shadow).rectangle(
            [pad + ox, pad + oy, pad + w + ox, pad + h + oy], fill=(0, 0, 0, alpha)
        )
        shadow = shadow.filter(ImageFilter.GaussianBlur(blur))
        canvas.alpha_composite(shadow)
        canvas.alpha_composite(img_rgb.convert("RGBA"), (pad, pad))
        return canvas

    # ── Watermark ──────────────────────────────────────────────────────────────

    def _font(self, size: int):
        for name in ("DejaVuSans-Bold.ttf", "DejaVuSans.ttf", "Arial.ttf", "arial.ttf"):
            try:
                return ImageFont.truetype(name, size)
            except Exception:
                continue
        try:
            return ImageFont.load_default(size=size)
        except Exception:
            return ImageFont.load_default()

    def _watermark(self, canvas: Image.Image, text: str) -> Image.Image:
        """Tiled diagonal watermark across the whole image so a clean copy can't
        be lifted from the public preview (can't be cropped out)."""
        text = (text or "PREVIEW").strip()
        W, H = canvas.size
        layer = Image.new("RGBA", (W * 2, H * 2), (0, 0, 0, 0))
        draw = ImageDraw.Draw(layer)
        font = self._font(42)
        # Dense enough that a clean copy can't be cropped from between marks, but
        # light enough to keep the preview attractive.
        step_x, step_y = 300, 150
        for y in range(0, H * 2, step_y):
            for x in range(0, W * 2, step_x):
                draw.text((x + 2, y + 2), text, font=font, fill=(0, 0, 0, 55))
                draw.text((x, y), text, font=font, fill=(255, 255, 255, 105))
        layer = layer.rotate(30, resample=Image.BICUBIC, expand=False)
        layer = layer.crop(((W * 2 - W) // 2, (H * 2 - H) // 2, (W * 2 + W) // 2, (H * 2 + H) // 2))
        out = canvas.convert("RGBA")
        out.alpha_composite(layer)
        return out.convert("RGB")
